language: ruby
rvm:
- 2.3.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install: gem install jekyll html-proofer
script: jekyll build && htmlproofer --http-status-ignore "999" check_html=true ./_site

sudo: false
exclude: [vendor]
